//
//  QY_jclient_jrm_protocol_Marco.h
//  QianYan_Ios
//
//  Created by 虎猫儿 on 15/4/28.
//  Copyright (c) 2015年 虎猫儿. All rights reserved.
//

#ifndef QianYan_Ios_QY_jclient_jrm_protocol_Marco_h
#define QianYan_Ios_QY_jclient_jrm_protocol_Marco_h

#warning 根据文档编号设计，如有变化，请更改。
typedef NS_ENUM (long,JRM_REQUEST_OPERATION_TYPE) {
    JRM_REQUEST_OPERATION_TYPE_DEVICE_LOGIN = 211 ,
    JRM_REQUEST_OPERATION_TYPE_USER_REGISTE = 251 ,
    JRM_REQUEST_OPERATION_TYPE_USER_LOGIN = 252 ,
};


/**
 *  协议版本 <<JRM通信协议(2015-4-29 10.41.11 3120)>>
 */

#define JRM_DATA_LENGTH_Len 2
#define JRM_DATA_CMD_Len 4


//--------------------------------------------------

#define DEVICE_TYPE_SIZE 4
#define DEVICE_PASSWD_SIZE 32
#define DEVICE_ID_SIZE 16
#define USERID_SIZE 16
#define USERNAME_SIZE 32
#define USEREMAIL_SIZE 32

#define USERPWD_SIZE 32
#define USER_GENDER_SIZE 8
#define NICKNAME_SIZE 32
#define IP_MEM_SIZE 16
#define PORT_MEM_SIZE 8
#define MEDIA_SUB_SIZE 32
#define LOCATION_SIZE 64
#define USER_SIGN_SIZE 128
#define SCULPTURE_NAME_SIZE 128

#define USER_VERIFY_SIZE 16
#define JIPNC_INJSS_STREAM_ADDR_LEN 30
#define MAX_SINGLE_DATA_SIZE 128

typedef NS_ENUM(NSInteger, JOSEPH_COMMAND) {
    //JSS
    JSS_ID2JRM_ERR = 1,
    JRM_ACTIVED_JSS,
    JSS_REPORT_JIPNC_ADDR,
    JSS_REPORT_JIPNC_ADDR_REPLY,
    JSS2JRM_HB_REPLY,
    
    //JPC
    
    JPC_REQUEST_HOWMANY_IPNC = 10,
    JPC_REPLY2JPC_HOWMANY_IPNC,
    JPC_REQUEST_IPNC_INFO,
    JRM2JPC_IPNC_INFO,
    JPC_PUSH_IPNC_REMARK,
    JPC_PUSH_IPNC_REMARK_REPLY,
    
    
    
    JCLIENT_REQUEST_LOGIN = 20,
    JCLIENT_REQUEST_LOGIN_REPLY,
    JCLIENT_GET_IPNC_LIST,
    JCLIENT_GET_IPNC_LIST_REPLY,
    
    
    JCLIENT_GET_IPNC_INFO,
    JCLIENT_GET_IPNC_INFO_REPLY,
    JCLIENT_GET_IPNC_VER,
    JCLIENT_GET_IPNC_INFO_WITH_DOMAIN,
    
    
    //JIPNC
    JIPNC_REQUEST_JSS = 30,
    JIPNC_REPORT_VERSION,
    JIPNC_ADD_MY_OWNER,
    JIPNC_REQUEST_MY_OWNER,
    JIPNC_REQUEST_JSTORE,
    JIPNC_REQUEST_JSTORE_WITH_DOMAIN,
    JIPNC_REQUEST_JSS_WITH_DOMAIN,
    JIPNC_REQUEST_JPRO_WITH_DOMAIN,
    
    
    // NEW ....................................................
    
    // ALL
    LOGIN2JRM_REQUEST_CMD = 40,
    LOGIN2JRM_REPLY_CMD,
    LOGIN2JRM_REPLY_ERR,
    
    DEVICE_LOGIN2JRM_CMD = 43,
    DEVICE_LOGIN2JRM_OK,
    DEVICE_LOGIN2JRM_ERR,
    
    DEVICE2JRM_HB,
    DEVICE2JRM_HB_REPLY,
    
    
    
    // JSS-JIPNC
    JSS_REPORT_JIPNC,
    JSS_REPORT_JSS,
    JSS_REPORT_JSS_WITH_DOMAIN,
    JSS_REQUEST_JPRO_WITH_DOMAIN,
    
    
    JSTORE_REPORT_JSTORE = 80,
    JSTORE_REPORT_JSTORE_WITH_DOMAIN,
    REQUEST_JRM = 100,
    REQUEST_JRM_REPLY,
    
    CONNECT_JSS = 200,
    CONNECT_JSS_OK,
    
    
    JCLIENT_GET_IPNC_HOWMANY = 300,
    JCLIENT_GET_IPNC_HOWMANY_REPLY,
    JCLIENT_GET_FRIEND_HOWMANY,
    JCLIENT_GET_FRIEND_HOWMANY_REPLY,
    
    JCLIENT_GET_FRIEND_LIST,
    JCLIENT_GET_FRIEND_LIST_REPLY,
    
    JCLIENT_ADD_FRIEND,
    JCLIENT_DEL_FRIEND,
    
    
    JCLIENT_GET_USER_INFO = 400,
    JCLIENT_GET_USER_INFO_REPLY,
    
    JCLIENT_SET_USER_INFO,
    JCLIENT_SET_USER_INFO_REPLY,
    JCLIENT_SET_USER_INFO_REPLY_ERR,
    
    JCLIENT_GET_USER_SCULPTURE,
    JCLIENT_GET_USER_SCULPTURE_REPLY,
    
    JCLIENT_SET_USER_SCULPTURE,
    JCLIENT_SET_USER_SCULPTURE_REPLY,
    
    JCLIENT_CHECK_USERNAME_INDB = 409,
    JCLIENT_CHECK_USERNAME_IS_INDB,
    JCLIENT_CHECK_USERNAME_NOT_INDB = 411,
    
    JCLIENT_REG_NEW_USER,
    JCLIENT_REG_NEW_USER_REPLY,
    JCLIENT_REG_NEW_USER_NAME_INVALID,
    
    JCLIENT_SET_USER_USERNAME = 415,
    JCLIENT_GET_USER_USERNAME,
    JCLIENT_SET_USER_PASS,
    
    JCLIENT_GET_USER_PASS =418,
    JCLIENT_SET_USER_PHONE,
    JCLIENT_GET_USER_PHONE,
    JCLIENT_SET_USER_EMAIL,
    JCLIENT_GET_USER_EMAIL,
    JCLIENT_SET_USER_NICKNAME,
    JCLIENT_GET_USER_NICKNAME,
    JCLIENT_SET_USER_SIGN = 425,
    JCLIENT_GET_USER_SIGN,
    JCLIENT_SET_USER_LOCATION,
    JCLIENT_GET_USER_LOCATION,
    JCLIENT_SET_USER_GENDER,
    JCLIENT_GET_USER_GENDER,
    
    JCLIENT_SET_FRIEND_NICKNAME = 431,
    JCLIENT_GET_FRIEND_NICKNAME,
    JCLIENT_SET_FRIEND_DESCRIBE,
    JCLIENT_GET_FRIEND_DESCRIBE,
    
    
    JCLIENT_ADD_IPNC_SHARE = 435,
    JCLIENT_DEL_IPNC_SHARE,
    
    
    JCLIENT_SET_IPNC_NICKNAME,
    JCLIENT_GET_IPNC_NICKNAME,
    
    JCLIENT_GET_USER_ID = 439,
    
    JCLIENT_GET_FRIEND_SCULPTURE,
    GET_JMSG_ADDR =441,
    
    GET_JIPNC_SUBADDR_IN_JSS,
    
    JCLIENT_GET_IPNC_OWNER_ID,
    
    JCLIENT_ADD_MY_OWN_IPNC = 461,
    JCLIENT_DEL_MY_OWN_IPNC,
    
    JCLIENT_GET_USER_ID_BY_PHONE = 470,
    JCLIENT_GET_USER_ID_BY_EMAIL = 471,
    
    JCLIENT_BIND_EMAIL_FOR_USER = 479,
    JCLIENT_RESET_PASSWD_BY_EMAIL = 480,
    JCLIENT_RESET_PASSWD_BY_PHONE = 481,
    JCLIENT_VERIFY_USER_BY_EMAIL = 482,
    
    JCLIENT_GET_OLD_USER_SERIES = 483,
    JCLIENT_GET_NEW_USER_SERIES = 484,
    JCLIENT_IPNC_SHARE_FOR_FRIEND_LIST = 490,
    JCLIENT_VERIFY_USER_PHONE = 491,
    JCLIENT_UNBIND_EMAIL_FOR_USER = 492,
    
    JCLIENT_GET_PUBLIC_IPNC_HOWMANY = 501,
    JCLIENT_GET_PUBLIC_IPNC_LIST = 502,
    JCLIENT_GET_PUBLIC_IPNC_INFO = 503,
    JCLIENT_GET_UPDATE_INFO = 504,
    JCLIENT_GET_USER_JPRO = 505,
    JCLIENT_GET_USER_JSS = 506,
    JCLIENT_GET_IPNC_JPRO = 507,
    JCLIENT_GET_IPNC_JSS = 508,
    JCLIENT_CHECK_USERNAME_PHONE = 509,
    JCLIENT_LOGIN_BY_OPENID = 510,
    JCLIENT_REGISTER_BY_OPENID = 511,
    JCLIENT_SET_USERNAME_BY_OPENID = 512,
    
    DEVICE_LOGIN2JRM_OPEN_CMD=600,
    JCLIENT_OPEN_REG_NEW_USER,
    JCLIENT_OPEN_REG_NEW_USER_REPLY,
    
    // reserved
    USER_IS_NULL = 65498,
    USEREMAIL_IS_NULL = 65499,
    JOSEPH_COMMAND_OK=65500,
    JOSEPH_COMMAND_ERR,
    JOSEPH_COMMAND_NULL
};

//安卓和IOS 都是 JOSEPH_DEVICE_JCLIENT = 30 ;
typedef NS_ENUM(NSInteger, JOSEPH_DEVICE_TYPE) {
    //*****************res 1**************************
    JOSEPH_DEVICE_JDAS = 1,
    JOSEPH_DEVICE_JRM = 10,
    JOSEPH_DEVICE_JSS = 20,
    JOSEPH_DEVICE_JCLIENT = 30,
    JOSEPH_DEVICE_JIPNC = 130,
    JOSEPH_DEVICE_JSTORE= 140,
    JOSEPH_DEVICE_JVRS =300,
    
    //*****************wuxi 1**************************
    JOSEPH_DEVICE_JSS_WUXI_1 = 611,
    JOSEPH_DEVICE_JCLIENT_WUXI_1 = 612,
    JOSEPH_DEVICE_JIPNC_WUXI_1 = 613,
    JOSEPH_DEVICE_JSTORE_WUXI_1= 614,
    JOSEPH_DEVICE_JVRS_WUXI_1 =615,
    
    //*****************wuxi 2**************************
    JOSEPH_DEVICE_JSS_WUXI_2 = 621,
    JOSEPH_DEVICE_JCLIENT_WUXI_2 = 622,
    JOSEPH_DEVICE_JIPNC_WUXI_2 = 623,
    JOSEPH_DEVICE_JSTORE_WUXI_2= 624,
    JOSEPH_DEVICE_JVRS_WUXI_2 =625,
    
    //*****************nanjing 1**************************
    JOSEPH_DEVICE_JSS_NANJING_1 = 711,
    JOSEPH_DEVICE_JCLIENT_NANJING_1 = 712,
    JOSEPH_DEVICE_JIPNC_NANJING_1 = 713,
    JOSEPH_DEVICE_JSTORE_NANJING_1= 714,
    JOSEPH_DEVICE_JVRS_NANJING_1 =715,
    
    //*****************nanjing 2**************************
    JOSEPH_DEVICE_JSS_NANJING_2 = 721,
    JOSEPH_DEVICE_JCLIENT_NANJING_2 = 722,
    JOSEPH_DEVICE_JIPNC_NANJING_2 = 723,
    JOSEPH_DEVICE_JSTORE_NANJING_2= 724,
    JOSEPH_DEVICE_JVRS_NANJING_2 =725,
    
    //*****************nanjing 3**************************
    JOSEPH_DEVICE_JSS_NANJING_3 = 731,
    JOSEPH_DEVICE_JCLIENT_NANJING_3 = 732,
    JOSEPH_DEVICE_JIPNC_NANJING_3 = 733,
    JOSEPH_DEVICE_JSTORE_NANJING_3= 734,
    JOSEPH_DEVICE_JVRS_NANJING_3 =735,
    
    //*****************nanjing 4**************************
    JOSEPH_DEVICE_JSS_NANJING_4 = 741,
    JOSEPH_DEVICE_JCLIENT_NANJING_4 = 742,
    JOSEPH_DEVICE_JIPNC_NANJING_4 = 743,
    JOSEPH_DEVICE_JSTORE_NANJING_4= 744,
    JOSEPH_DEVICE_JVRS_NANJING_4 =745,
    
    //*****************nanjing 5**************************
    JOSEPH_DEVICE_JSS_NANJING_5 = 751,
    JOSEPH_DEVICE_JCLIENT_NANJING_5 = 752,
    JOSEPH_DEVICE_JIPNC_NANJING_5 = 753,
    JOSEPH_DEVICE_JSTORE_NANJING_5= 754,
    JOSEPH_DEVICE_JVRS_NANJING_5 =755,
    
    //*****************reserved 1**************************
    JOSEPH_DEVICE_JSS_RESERVED_1 = 811,
    JOSEPH_DEVICE_JCLIENT_RESERVED_1 = 812,
    JOSEPH_DEVICE_JIPNC_RESERVED_1 = 813,
    JOSEPH_DEVICE_JSTORE_RESERVED_1= 814,
    JOSEPH_DEVICE_JVRS_RESERVED_1 =815,
    
    //*****************reserved 2**************************
    JOSEPH_DEVICE_JSS_RESERVED_2 = 821,
    JOSEPH_DEVICE_JCLIENT_RESERVED_2 = 822,
    JOSEPH_DEVICE_JIPNC_RESERVED_2 = 823,
    JOSEPH_DEVICE_JSTORE_RESERVED_2= 824,
    JOSEPH_DEVICE_JVRS_RESERVED_2 =825,
    
    //*****************reserved 3**************************
    JOSEPH_DEVICE_JSS_RESERVED_3 = 831,
    JOSEPH_DEVICE_JCLIENT_RESERVED_3 = 832,
    JOSEPH_DEVICE_JIPNC_RESERVED_3 = 833,
    JOSEPH_DEVICE_JSTORE_RESERVED_3= 834,
    JOSEPH_DEVICE_JVRS_RESERVED_3 =835,
    
    //*****************reserved 4**************************
    JOSEPH_DEVICE_JSS_RESERVED_4 = 841,
    JOSEPH_DEVICE_JCLIENT_RESERVED_4 = 842,
    JOSEPH_DEVICE_JIPNC_RESERVED_4 = 843,
    JOSEPH_DEVICE_JSTORE_RESERVED_4= 844,
    JOSEPH_DEVICE_JVRS_RESERVED_4 =845,
    
    //*****************reserved 5**************************
    JOSEPH_DEVICE_JSS_RESERVED_5 = 851,
    JOSEPH_DEVICE_JCLIENT_RESERVED_5 = 852,
    JOSEPH_DEVICE_JIPNC_RESERVED_5 = 853,
    JOSEPH_DEVICE_JSTORE_RESERVED_5= 854,
    JOSEPH_DEVICE_JVRS_RESERVED_5 =855,
    
    //**************************************************
    JOSEPH_DEVICE_TYPE_NULL	= -1
} ;

#endif
